.PHONY: all
all: install

.PHONY: install
install:
	./scripts/makefile/install.sh

.PHONY: test
test:
	./scripts/makefile/test.sh

.PHONY: coverage
coverage:
	./scripts/makefile/coverage.sh

.PHONY: lint
lint:
	./scripts/makefile/lint.sh

.PHONY: clean
clean:
	./scripts/makefile/clean.sh

.PHONY: tidy
tidy:
	./scripts/makefile/tidy.sh

.PHONY: database
database:
	./scripts/makefile/database.sh

.PHONY: docs
docs:
	./scripts/makefile/docs.sh

.PHONY: fmt
fmt:
	./scripts/makefile/fmt.sh
