---
project_name: mockery
before:
    hooks:
      - go mod download
builds:
  - main: ./main.go
    binary: mockery
    ldflags:
      - -s -w -X github.com/conneroisu/seltabls/v2/pkg/logging.SemVer=v{{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
checksum:
    name_template: "checksum.txt"
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
dockers:
  - image_templates: ["conneroisu/seltabls:{{ .Tag }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates: ["conneroisu/seltabls:{{ .Tag }}-arm64"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: conneroisu/seltabls:{{ .Tag }}
    image_templates:
      - conneroisu/seltabls:{{ .Tag }}-amd64
      - conneroisu/seltabls:{{ .Tag }}-arm64
  - name_template: conneroisu/seltabls:v{{ .Major }}
    image_templates:
      - conneroisu/seltabls:{{ .Tag }}-amd64
      - conneroisu/seltabls:{{ .Tag }}-arm64
  - name_template: conneroisu/seltabls:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - conneroisu/seltabls:{{ .Tag }}-amd64
      - conneroisu/seltabls:{{ .Tag }}-arm64
  - name_template: conneroisu/seltabls:latest
    image_templates:
      - conneroisu/seltabls:{{ .Tag }}-amd64
      - conneroisu/seltabls:{{ .Tag }}-arm64
brews:
  - homepage: https://github.com/conneroisu/seltabls
    description: "A mock code autogenerator for Go"
    tap:
        owner: conneroisu
        name: homebrew-tap
        token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    test: |
        system "#{bin}mockery --version"
