package lsp

// CompletionRequest is a request for a completion to the language server
type CompletionRequest struct {
	Request
	Params CompletionParams `json:"params"`
}

// CompletionParams is a struct for the completion params
type CompletionParams struct {
	TextDocumentPositionParams
}

// CompletionResponse is a response for a completion to the language server
type CompletionResponse struct {
	Response
	Result []CompletionItem `json:"result"`
}

// CompletionItem is a struct for a completion item
type CompletionItem struct {
	Label         string `json:"label"`
	Detail        string `json:"detail"`
	Documentation string `json:"documentation"`
}

type AutoGenerated struct {
	Method string `json:"method"`
	ID     int    `json:"id"`
	Params struct {
	} `json:"params"`
	Jsonrpc string `json:"jsonrpc"`
}
