blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
    about: Browse the IntelliJ Platform Gradle Plugin documentation.
  - name: Getting Help
    url: https://plugins.jetbrains.com/docs/intellij/getting-help.html
    about: For help with plugin development.
