// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package master

type Selector struct {
	ID       int64  `db:"id" json:"id"`
	Selector string `db:"selector" json:"selector"`
	Url      string `db:"url" json:"url"`
	Context  string `db:"context" json:"context"`
}
