name: Project Verification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  gradleValidation:
    name: Gradle Validation
    uses: ./.github/workflows/reusable-gradleValidation.yml
