// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlite3

type Url struct {
	ID       string `db:"id" json:"id"`
	Url      string `db:"url" json:"url"`
	Encoding string `db:"encoding" json:"encoding"`
}
