// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlite3

import (
	"context"
)

const getURLs = `-- name: GetURLs :many
SELECT id, url, encoding FROM urls
`

// GetURLs
//
//	SELECT id, url, encoding FROM urls
func (q *Queries) GetURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.Url, &i.Encoding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
