name: Test Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      id: checkout
    # - name: Setup upterm session
    #   id: term
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## If no one connects after 5 minutes, shut down server.
    #     wait-timeout-minutes: 5
    - name: Setup SSH
      id: ssh-setup
      run: |
        sudo apt-get install tmate
    - name: Set up tmate session in background
      id: tmate
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > ssh_url.txt
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}' > web_url.txt
        echo "::set-output name=tmate_ssh::$(cat ssh_url.txt)"
        echo "::set-output name=tmate_web::$(cat web_url.txt)"

    - name: Print tmate URLs
      run: |
        echo "Tmate SSH URL: ${{ steps.tmate.outputs.tmate_ssh }}"
        echo "Tmate Web URL: ${{ steps.tmate.outputs.tmate_web }}"
    - name: Set Up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Test
      id: test
      uses: robherley/go-test-action@v0

    - name: Custom Tests
      id: custom-tests
      run: make test

    - name: Upload coverage reports to Codecov
      id: codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Save output
      id: save-output
      run: |
        result=$(cat some_output_file.txt)
        echo "::set-output name=result::$result"
