name: Test Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x', '1.22.x' ]
    steps:
    - uses: actions/checkout@v4
      id: checkout
    - name: Set Up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Test
      id: test
      uses: robherley/go-test-action@v0

    - name: Custom Tests
      id: custom-tests
      run: make test

    - name: Upload coverage reports to Codecov
      id: codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Sleep for 100 seconds
      run: sleep 100
